pipeline {
    agent any
    tools {
        maven 'jenkins-maven'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Code Quality Check via SonarQube') {
            steps {
                script {
                withSonarQubeEnv("SonarQube") {
                sh "mvn sonar:sonar \
                    -Dsonar.projectKey=SonarTest \
                    -Dsonar.host.url=http://192.168.0.105:9000"
                    }
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
